### ISSUE TITLE
Use of msix for Windows?

### ISSUE THREAD

**Issue by alexcmgit** [zTomz/OpenScribe#1]
Windows defender and Chrome blocked 7 times before I could finally execute the app, I guess you can fix that by packaging the windows build as msix: https://pub.dev/packages/msix.

I missed the `CTRL + F` feature but the UI is overall smooth and intuitive, nice!

**Comment by zTomz** [comment]
Thanks for the feedback, for me it was exactly the opposite. I had no problems with the .zip folder, but with an msix launcher. I'll still provide one tonight.

With the `Ctrl + F` feature you mean a search feature?

**Comment by alexcmgit** [comment]
Okay, no prob.

Yes, `CTRL + F` -> search feature.

**Comment by zTomz** [comment]
Provided the .msix installer in the latest release. I am not sure if it works, would be nice if you could let me know if it works on your machine.

**Comment by alexcmgit** [comment]
Not working yet

![image](https://github.com/zTomz/OpenScribe/assets/51419598/05185008-c447-4f9f-bed9-657f2ec57181)

It now blocks from installing/running

**Comment by zTomz** [comment]
Can you try doing what I described in the readme. I am not sure if you can do this on your machine. If you have any experience with msix. It would be nice, if you can help me get it working

**Comment by zTomz** [comment]
I have just submitted the OpenScribe.exe file to Releases. It is a self-extracting archive and should work, the security messages that appear can be easily clicked away. I'm not sure why there are so many security messages.

**Comment by alexcmgit** [comment]
The self-extracting .exe worked gracefully, the only thing missing is the right installation folder, is that possible to configure the self-extracting zip to offer the `ProgramFiles\OpenScribe` as the initial folder?

**Comment by alexcmgit** [comment]
Also, I've found this tool: https://wixtoolset.org/docs/intro/

To generate a .msi installer. It may be helpful or not.

---

Related links:

- https://stackoverflow.com/questions/4159737/how-can-i-create-a-msi-file-for-a-java-program-eclipse


Chat GPT answer to `How can I generate the .msi from a flutter desktop source code`:

<summary>
  <details>

Creating an .msi installer from a Flutter desktop source code involves a series of steps, and it's a bit different from converting an .exe to an .msi. Here's a general overview of how you can package a Flutter desktop application into an .msi installer:

1. **Prepare Your Flutter Desktop Application:**
   - Make sure your Flutter desktop application is complete and functional.
   - Verify that it can be built and run on the target Windows system.

2. **Install Necessary Tools:**
   - Install Flutter on your development system if you haven't already.
   - Make sure you have Flutter Desktop support installed.

3. **Build Your Application:**
   - Use the Flutter commands to build your application for the Windows platform. You can do this with `flutter build windows`.

4. **Create an .msi Installer:**
   - To create an .msi installer, you'll need to use a separate tool, as Flutter's build process primarily generates an executable, not an installer.

5. **Use WiX Toolset:**
   - The WiX Toolset is a popular choice for creating Windows installers (including .msi files). You can download and install WiX from the official website: https://wixtoolset.org/
   - Learn how to use WiX to create an installer package for your application. This typically involves creating an XML configuration file that describes the installer's behavior.

6. **Define Installation Steps:**
   - In your WiX configuration file, define the installation steps, including specifying the executable to install, creating shortcuts, and configuring any registry settings or other dependencies your application requires.

7. **Build the .msi Installer:**
   - Use the WiX Toolset to build your .msi installer. This process will compile your configuration file and create the .msi package.

8. **Test the Installer:**
   - Before distributing your application, thoroughly test the installer on a Windows system to ensure that it installs your Flutter desktop application correctly.

9. **Distribute Your Application:**
   - Once you have a working .msi installer, you can distribute it to users. Make sure to comply with any licensing and distribution requirements for your application.

Keep in mind that creating an installer for a Flutter desktop application is a relatively complex process. You may also need to consider code-signing your installer to establish trust with users and avoid potential security warnings during installation.

Also, be aware that the process may vary slightly depending on the specific dependencies and requirements of your Flutter desktop application. You might need to customize the WiX configuration to suit your application's needs.

</details>

</summary>

**Comment by zTomz** [comment]
Thanks, that looks promising. I'll look at it. As far as I know, the self-extracting archive is not able to automatically specify a target folder, but I will also research it again. Thanks for the feedback so far

**Comment by zTomz** [comment]
Thanks, that looks promising. I'll look at it. As far as I know, the self-extracting archive is not able to automatically specify a target folder, but I will also research it again. Thanks for the feedback so far

**Comment by zTomz** [comment]
I created a installer, which is provided in the newest release. I will close this issue, can you please create a new issue for the `CTRL + F` feature.

**Comment by alexcmgit** [comment]
Did you create the installer using what tool? Do you mind sharing how did you do that?

**Comment by zTomz** [comment]
I'm in the process of writing an article on Medium. I'll share the link here when I'm done.

**Comment by zTomz** [comment]
Link to the medium article: https://medium.com/@tommyyy/how-to-publish-a-flutter-windows-application-outside-the-microsoft-store-49bb9d25555c
