### ISSUE TITLE
App doesn't run if the machine doesn't have Microsoft Visual Studio installed

### ISSUE THREAD

**Issue by alexcmgit** [zTomz/OpenScribe#2]
You can reproduce this error by trying to execute the app inside the Windows Sandbox.

Please, see also: https://stackoverflow.com/a/67836157/11793117

**Comment by zTomz** [comment]
Ok, I'll look at it

**Comment by zTomz** [comment]
I fixed the issus, now you can download the `openscribe_setup.exe` and it will run.

#### NOTE: Only the `openscribe_setup.exe`, can run on computers without the build tools installed.

Thanks for adding the issue
